using System;
using System.Collections.Generic;
using HarmonyLib;
using L2Base;
using L2Flag;
using LaMulana2Archipelago.Archipelago;
using LaMulana2Archipelago.Managers;
using LaMulana2RandomizerShared;
using LM2RandomiserMod;
using UnityEngine;

namespace LaMulana2Archipelago.Patches
{
    /// <summary>
    /// Workaround for seeds generated by Archipelago &lt; 0.6.7.
    ///
    /// Those generators leak the generic AP-trash filler ids (coins 901-906, weights
    /// 907-910, ammo bundles 911-917) into the binary seed instead of translating them
    /// to the internal FakeScan/FakeItem ids the client has ItemInfo for. The result is
    /// locations the client can't resolve: murals grant a vanilla item, chests glitch,
    /// shop slots never sell out.
    ///
    /// This file is the ENTIRE workaround. It only does anything when a seed actually
    /// contains leaked ids (see <see cref="Active"/>), and the reward itself always comes
    /// from the AP echo (so these become effectively one-time checks). The goal is only to
    /// let AP register that the location was checked.
    ///
    /// Touch-points in other files are tagged "LEAKED-FILLER WORKAROUND (067)":
    ///   • SeedFlagMapBuilder.TryAdd          -> RegisterLeakedFillerLocation (gate + flag)
    ///   • LocationFlagMap.Initialize         -> Reset
    ///   • SnapMenuPatch.Prefix (murals)      -> TryHandleMural
    ///   • SceneRandomizer.ChangeChests       -> MaybeInjectChestFlag
    ///   • SceneRandomizer.ChangeEventItems   -> MaybeInjectEventItemFlag (freestanding)
    ///   • SceneRandomizer.ChangeTalk* (NPCs) -> BuildNpc*
    ///   • SceneRandomizer.CreateSetItemString / CreateGetFlagString (shops, purchasable)
    /// Delete this file + those tagged lines once 0.6.7+ is universal.
    /// </summary>
    internal static class Filler067Workaround
    {
        /// <summary>True once a leaked filler id has been seen in the current seed.</summary>
        public static bool Active { get; private set; }

        /// <summary>
        /// Synthetic per-location sheet-31 flag base for leaked-filler chests. Sits above
        /// the AP-placeholder flag ceiling (FlagOffset 225 + 9999 = 10224) and, with max
        /// LocationID ~716, well under the 0xFFFF flag-key limit, so it never collides.
        /// VirtualFlagManager handles any sheet-31 flag &gt;= 225.
        /// </summary>
        public const int SyntheticFlagBase = 20000;

        public static bool IsLeakedFiller(int id) => id >= 901 && id <= 917;

        public static int SyntheticFlag(int locationIdValue) => SyntheticFlagBase + locationIdValue;

        /// <summary>Reset at the start of each flag-map build (reconnect / new seed).</summary>
        public static void Reset() => Active = false;

        // ── SeedFlagMapBuilder hook ──────────────────────────────────────────────
        /// <summary>
        /// Called for a location whose item has no ItemInfo. If it's leaked filler,
        /// engage the workaround and register a synthetic sheet-31 flag → location so a
        /// chest get-flag can report it. Returns true if handled.
        /// </summary>
        public static bool RegisterLeakedFillerLocation(int itemId, LocationID location,
            Action<int, int, LocationID> addNumeric)
        {
            if (!IsLeakedFiller(itemId)) return false;

            if (!Active)
            {
                Active = true;
                Plugin.Log.LogWarning("[067] Leaked AP-trash filler ids (901-917) found in seed — "
                    + "pre-0.6.7 workaround ENGAGED. Filler rewards are one-time (delivered via AP).");
            }

            addNumeric?.Invoke(31, SyntheticFlag((int)location), location);
            return true;
        }

        // ── SnapMenuPatch hook (murals) ──────────────────────────────────────────
        /// <summary>
        /// Mural holds leaked filler: report the check and end the scan cleanly instead
        /// of falling into the vanilla hardcoded-item path. Reward arrives via the echo.
        /// </summary>
        public static bool TryHandleMural(L2System sys, Traverse t, LocationID locationID, ItemID itemID)
        {
            if (!Active || locationID == LocationID.None || !IsLeakedFiller((int)itemID)) return false;

            sys.setKeyBlock(false);
            CheckManager.NotifyLocation(locationID);
            t.Field("sta").SetValue(3); // NoContents — end the scan, no grant dialog
            Plugin.Log.LogInfo($"[067] Mural leaked filler {locationID}: reported via NotifyLocation");
            return true;
        }

        // ── Shops ────────────────────────────────────────────────────────────────
        // Leaked filler in a shop is sold as a free (price 0) "AP Item {synthFlag}" slot,
        // handled directly in SceneRandomizer.CreateSetItemString / CreateGetFlagString
        // (rides the existing AP-Item shop pipeline). No hook needed here.

        // ── SceneRandomizer hooks (chests + freestanding) ────────────────────────
        /// <summary>
        /// Inject a synthetic sheet-31 get-flag onto a leaked-filler chest so opening it
        /// reports the check (the flag is registered in RegisterLeakedFillerLocation).
        /// Reward via echo.
        /// </summary>
        public static void MaybeInjectChestFlag(TreasureBoxScript chest, ItemID itemID, LocationID locationID)
        {
            if (!Active || locationID == LocationID.None || !IsLeakedFiller((int)itemID)) return;
            if (chest == null || chest.itemObj == null) return;

            int flag = SyntheticFlag((int)locationID);

            // Chest shows "open" once the synthetic flag is set, so it isn't re-grabbable.
            // Mirrors ChangeChestItemFlags: rewrite the seet-2 sentinel in openFlags to
            // (31, synthFlag) with compare value 1.
            if (chest.openFlags != null)
            {
                foreach (L2FlagBoxParent parent in chest.openFlags)
                {
                    if (parent?.BOX == null) continue;
                    foreach (L2FlagBox box in parent.BOX)
                    {
                        if (box.seet_no1 == 2)
                        {
                            box.seet_no1 = 31;
                            box.flag_no1 = flag;
                            box.flag_no2 = 1;
                        }
                    }
                }
            }

            EventItemScript item = chest.itemObj.GetComponent<EventItemScript>();
            // itemObj is a shared prefab whose rewrite outlives the scene; snapshot
            // it so a disconnect can revert this chest to vanilla.
            Managers.WorldDataRestore.CaptureItemPrefab(item);
            MaybeInjectEventItemFlag(item, itemID, locationID);
        }

        /// <summary>
        /// Inject the synthetic flags onto a leaked-filler freestanding / event item (and
        /// any EventItemScript-backed pickup, incl. glossary ROMs). Sets:
        ///   • itemActiveFlag → active only while synthFlag == 0 (so it vanishes once taken),
        ///   • itemGetFlags   → set synthFlag = 1 on pickup (reports the check),
        ///   • itemLabel      → "AP Item" so the local grant is suppressed (reward via echo).
        /// </summary>
        public static void MaybeInjectEventItemFlag(EventItemScript item, ItemID itemID, LocationID locationID)
        {
            if (!Active || locationID == LocationID.None || !IsLeakedFiller((int)itemID)) return;
            if (item == null) return;

            int flag = SyntheticFlag((int)locationID);

            item.itemActiveFlag = new L2FlagBoxParent[]
            {
                new L2FlagBoxParent
                {
                    BOX = new L2FlagBox[]
                    {
                        new L2FlagBox
                        {
                            seet_no1 = 31, flag_no1 = flag, seet_no2 = -1, flag_no2 = 0,
                            comp = COMPARISON.Equal, logic = LOGIC.NON,
                        }
                    }
                }
            };

            item.itemGetFlags = new L2FlagBoxEnd[]
            {
                new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 31, flag_no1 = flag, data = 1 }
            };
            item.itemLabel = "AP Item"; // suppressed by SetItemApPatch — no wrong local grant
            Plugin.Log.LogInfo($"[067] Leaked filler {locationID}: report via synthetic flag 31:{flag}");
        }

        // ── SceneRandomizer hooks (NPCs / dialogue) ──────────────────────────────
        // NPC items bake their get-flag into the dialogue SCRIPT (no EventItemScript to
        // inject), so leaked filler gets a talk-script that just sets the synthetic flag
        // (no [@take] → no wrong grant; reward via echo). The two builders mirror the two
        // ChangeTalkString* format signatures. Both return null when not leaked filler so
        // the caller falls back to its normal path.

        /// <summary>For ChangeTalkString: original has one slot {0} = item-script.</summary>
        public static string BuildNpcTalkString(LocationID locationID, ItemID itemID, string original)
        {
            if (!Active || !IsLeakedFiller((int)itemID)) return null;
            int flag = SyntheticFlag((int)locationID);
            Plugin.Log.LogInfo($"[067] NPC leaked filler {locationID}: report via synthetic flag 31:{flag}");
            return string.Format(original, $"[@setf,31,{flag},=,1]\n");
        }

        /// <summary>
        /// For ChangeTalkStringAndFlagCheck: original has {0}=sheet {1}=flag {2}=value
        /// {3}=item-script. We point the gate flag at the synthetic flag (give once).
        /// </summary>
        public static string BuildNpcTalkFlagCheckString(LocationID locationID, ItemID itemID, string original)
        {
            if (!Active || !IsLeakedFiller((int)itemID)) return null;
            int flag = SyntheticFlag((int)locationID);
            Plugin.Log.LogInfo($"[067] NPC(gated) leaked filler {locationID}: report via synthetic flag 31:{flag}");
            return string.Format(original, 31, flag, 0, $"[@setf,31,{flag},=,1]\n");
        }

        /// <summary>
        /// For ChangeTalkFlagCheck (gate only): original has {0}=sheet {1}=flag {2}=value.
        /// Points the gate at the synthetic flag so the NPC offers it once.
        /// </summary>
        public static string BuildNpcFlagCheckString(LocationID locationID, ItemID itemID, COMPARISON comp, string original)
        {
            if (!Active || !IsLeakedFiller((int)itemID)) return null;
            int flag = SyntheticFlag((int)locationID);
            return string.Format(original, 31, flag, comp == COMPARISON.Less ? 1 : 0);
        }
    }
}
